### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by jayeew** [sekharvth/chatbot-keras#2]
when i try to run chatbot_training.py, it show me a MemoryError on line 71.how to fix it, ple?

**Comment by trilokiDA** [comment]
> when i try to run chatbot_training.py, it show me a MemoryError on line 71.how to fix it, ple?

Are you find solution for this?

**Comment by jayeew** [comment]
> > when i try to run chatbot_training.py, it show me a MemoryError on line 71.how to fix it, ple?
> 
> Are you find solution for this?

sorry for late.
I have fixed it. It's the large data that cause the Memory Error. You can use fit_generator function and use a generator to get batch_size data everytime.
