### ISSUE TITLE
whatever i enter,  i got the same reply, a single word 'It', how can i fix it?

### ISSUE THREAD

**Issue by jayeew** [sekharvth/chatbot-keras#3]

**Comment by jayeew** [comment]
fixed it by myself. thank you

**Comment by khadijabibi567** [comment]
jiayiwang5 can you plz share the working code of this project ??? bcz here i ddnt find any weight files dicticonary file n  movies_lines .txt

**Comment by sekharvth** [comment]
Hi @khadijabibi567 , I haven't included weight files because I couldn't train properly on a CPU. Also the movie_lines.txt file is the same as the Cornell Movie Dialogue Corpus. A simple Google search will lead you to the data, and you can use that there. Closing for now.

**Comment by khadijabibi567** [comment]
Thank you
